name: hw1_env

dependencies:
  - python=3.6
  - numpy==1.19.5
  - pandas==1.2.3
  - pip:
      - pycaret==2.3.1
      - catboost==0.25.1
      - lightgbm==3.2.1
      - git+https://github.com/yotammarton/TransformDF2Numpy.git