name: hw1_env

dependencies:
  - pip
  - python=3.8
  - pip:
      - pycaret==2.2.3
      - numpy
      - pandas
      - catboost==0.25.1
      - lightgbm==3.2.1
      - git+https://github.com/yotammarton/TransformDF2Numpy.git
